version: '3'
services:
  openapi:
    image: swaggerapi/swagger-ui
    ports:
      - 8000:8080
    volumes:
      - ./openapi.yaml:/usr/share/nginx/html/openapi.yaml
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=plmoknijb
      - MYSQL_DATABASE=gin_go_api
      - MYSQL_USER=ubaid
      - MYSQL_PASSWORD=plmoknijb
    volumes:
      - ./data:/var/lib/mysql
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3333
    command: bin/air
    depends_on:
      - mysql
      - openapi
  backup:
    image: mysql
    command: sh -c '/backup.sh'
    depends_on:
      - mysql
    volumes:
      - ./backup:/backup
      - ./backup.sh:/backup.sh

  